
const categories = [
  { id: 1, name: 'Indian', image: require('../../assets/food_cat/masala-dosa.png') },
  { id: 2, name: 'Burger', image: require('../../assets/food_cat/burger.png') },
  { id: 3, name: 'Pizza', image: require('../../assets/food_cat/pizza.png') },
  { id: 4, name: 'Salad', image: require('../../assets/food_cat/salad.png') },

];
const icons = [
  { name: 'Bread', image: require('../../assets/food_icons/Bread.jpg') },
  { name: 'Chicken', image: require('../../assets/food_icons/Chicken.jpg') },
  { name: 'Oil', image: require('../../assets/food_icons/Cooking_Oil.jpg') },
  { name: 'Egg', image: require('../../assets/food_icons/Egg.jpg') },
  { name: 'Flour', image: require('../../assets/food_icons/Flour.jpg') },
  { name: 'Garlic', image: require('../../assets/food_icons/Garlic.jpg') },
  { name: 'Okra', image: require('../../assets/food_icons/Okra.jpg') },
  { name: 'Pizza', image: require('../../assets/food_icons/Pizza.jpg') },
  { name: 'Potatoes', image: require('../../assets/food_icons/Potato.jpg') },
  { name: 'Seasoning', image: require('../../assets/food_icons/Seasoning.jpg') },
  { name: 'Spices', image: require('../../assets/food_icons/Spice.jpg') },
  { name: 'Lemon', image: require('../../assets/food_icons/lemon.jpg') },
  { name: 'Panner', image: require('../../assets/food_icons/panner.jpg') },
  { name: 'Yogurt', image: require('../../assets/food_icons/Yogurt.jpg') },
  { name: 'Rice', image: require('../../assets/food_icons/Rice.jpg') },
  { name: 'Tomato', image: require('../../assets/food_icons/tomato.jpg') },
  { name: 'Urad Dal', image: require('../../assets/food_icons/dal.jpg') },
  { name: 'Vegetables', image: require('../../assets/food_icons/vegetables.jpg') },
  { name: 'Olives', image: require('../../assets/food_icons/Olive.jpg') },
  { name: 'Beef', image: require('../../assets/food_icons/Beef.jpg') },
  { name: 'Mozzarella', image: require('../../assets/food_icons/Mozzarella.jpg') },
  { name: 'Cream', image: require('../../assets/food_icons/Cream.jpg') },
  { name: 'Lettuce', image: require('../../assets/food_icons/lettuce.jpg') },
  { name: 'Bun', image: require('../../assets/food_icons/Bun.jpg') },
  { name: 'Mayonnaise', image: require('../../assets/food_icons/Mayonnaise.jpg') },
  { name: 'Cheese', image: require('../../assets/food_icons/Cheese.jpg') },
  { name: 'Basil', image: require('../../assets/food_icons/Basil.jpg') },
  { name: 'Crouton', image: require('../../assets/food_icons/crouton.jpg') },
  { name: 'Bell-pepper', image: require('../../assets/food_icons/bell_pepper.jpg') },
  { name: 'Feta', image: require('../../assets/food_icons/Feta.jpg') },
  { name: 'Salt', image: require('../../assets/food_icons/Salt.jpg') },
  { name: 'Onion', image: require('../../assets/food_icons/Onion.jpg') },
  { name: 'Pepperoni', image: require('../../assets/food_icons/Pepperoni.jpg') },
  { name: 'Milk', image: require('../../assets/food_icons/Milk.jpg') },

];
const foods = [
  {
    id: 1,
    name: 'Butter Chicken',
    ingredients: 'Chicken,Lemon,Garlic,Spices',
    price: '8.30',
    person: 2,
    duration: 1.10,
    categoryid: 1,
    image: require('../../assets/food/butter-chicken-curry.jpg'),
    details: 'Chicken is marinated in yogurt, spices, garlic and ginger, then later cooked in a tandoor, but it can also be pan fried, grilled or oven roasted. After that it is tossed with the simmered, richly seasoned tomato sauce.',
  },
  {
    id: 2,
    name: 'Pepperoni Pizza',
    ingredients: 'Flour,Pepperoni,Mozzarella',
    price: '7.10',
    person: 3,
    duration: 0.30,
    categoryid: 3,
    image: require('../../assets/food/pepperoni-pizza.jpg'),
    details: "Pepperoni pizza is an American pizza variety which includes one of the country's most beloved toppings. Pepperoni is actually a corrupted form of peperoni (one “p”), which denotes a large pepper in Italian, but nowadays it denotes a spicy salami, usually made with a mixture of beef, pork, and spices.",
  },
  {
    id: 3,
    name: 'Chicken Burger',
    ingredients: 'Chicken Meat,Seasoning,Binders,Spices',
    price: '5.10',
    person: 1,
    duration: 0.20,
    categoryid: 2,
    image: require('../../assets/food/chickenBurger.png'),
    details: "A chicken burger is a popular and versatile sandwich that features a patty made from ground or minced chicken meat, typically seasoned and cooked to perfection. ",
  },
  {
    id: 4,
    name: 'Garlic Naan',
    ingredients: 'Flour,Garlic,Spices,Yogurt',
    price: '9.55',
    person: 1,
    duration: 0.50,
    categoryid: 1,
    image: require('../../assets/food/garlic-naan.jpg'),
    details: "Garlic naan is a popular variation of traditional naan bread, which is a type of flatbread that originates from South Asia, particularly India. "
  },
  {
    id: 5,
    name: 'Malai Kofta',
    ingredients: 'Paneer,Potatoes,Vegetables,Spices, Flour',
    price: '9.55',
    person: 4,
    duration: 0.55,
    categoryid: 1,
    image: require('../../assets/food/malai-kofta.jpg'),
    details: "Malai kofta is a vegetarian dish made with deep-fried vegetable or paneer (Indian cottage cheese) dumplings served in a flavorful tomato-based gravy. ",
  },
  {
    id: 6,
    name: 'Samosa',
    ingredients: 'Flour, Oil, Potatoes, Spices, Garlic',
    price: '9.55',
    person: 1,
    duration: 0.25,
    categoryid: 1,
    image: require('../../assets/food/entrees.jpg'),
    details: "A samosa is a fried or baked pastry with a savory filling, including ingredients such as spiced potatoes, onions, and peas. It may take different forms, including triangular, cone, or half-moon shapes, depending on the region.",
  },

  {
    id: 7,
    name: "Vegetable Biryani",
    ingredients: "Rice, Vegetables, Spices, Potatoes, Onion, Oil",
    price: "11.99",
    person: 3,
    duration: 1.30,
    categoryid: 1,
    image: require('../../assets/food/Vegetable-Biryani.jpg'),
    details: "A delicious and flavorful rice dish made with vegetables, spices, and herbs."
  },
  {
    id: 8,
    name: "Tandoori Chicken",
    ingredients: "Chicken, Yogurt, Lemon, Oil, Spices",
    price: "12.99",
    person: 5,
    duration: 0.30,
    categoryid: 1,
    image: require('../../assets/food/Tandoori-Chicken.jpg'),
    details: "Tandoori chicken is a popular Indian dish known for its smoky, flavorful, and mildly spiced grilled or roasted chicken. "
  },
  {
    id: 9,
    name: "Paneer Tikka Masala",
    ingredients: "Panner, Lemon, Oil, Yogurt, Tomato, Spices",
    price: "13.99",
    person: 4,
    duration: 0.45,
    categoryid: 1,
    image: require('../../assets/food/Paneer-Tikka-Masala.jpg'),
    details: "Indian cheese marinated in spices, then grilled and cooked in a creamy tomato sauce."
  },
  {
    id: 10,
    name: "Chicken Tikka Masala",
    ingredients: "Chicken, Yogurt, Oil, Tomato, Cream, Spices",
    price: "14.99",
    person: 6,
    duration: 1.00,
    categoryid: 1,
    image: require('../../assets/food/Chicken-Tikka-Masala.webp'),
    details: "Chicken tikka masala is a popular Indian dish consisting of marinated and grilled chicken pieces served in a creamy tomato-based gravy. "
  },
  {
    id: 11,
    name: "Dosa",
    ingredients: "Rice, Oil, Spices, Urad Dal",
    price: "7.99",
    person: 2,
    duration: 0.35,
    categoryid: 1,
    image: require('../../assets/food/dosa.jpg'),
    details: "Dosa is a popular South Indian thin and crispy pancake made from fermented rice and urad dal (black gram) batter."
  },
  {
    id: 12,
    name: "Naan Bread",
    ingredients: "Flour, Yogurt, Milk, Oil",
    price: "4.99",
    person: 1,
    duration: 0.22,
    categoryid: 1,
    image: require('../../assets/food/naan.png'),
    details: "Naan bread is a popular type of flatbread that originated in South Asia, particularly in India. "
  },
  {
    id: 13,
    name: "Chicken Burger",
    ingredients: "Chicken, Bun, Lettuce, Tomato, Onion",
    price: "6.99",
    person: 1,
    duration: 0.20,
    categoryid: 2,
    image: require('../../assets/food/chickenBurger.png'),
    details: "A classic burger made with a chicken patty, bun, lettuce, tomato, onion, and mayonnaise."
  },
  {
    id: 14,
    name: "Beef Burger",
    ingredients: "Beef, Bun, Lettuce, Tomato, Onion, Mayonnaise",
    price: "7.99",
    person: 1,
    duration: 0.30,
    categoryid: 2,
    image: require('../../assets/food/Burger.jpg'),
    details: "A classic burger made with a beef patty, bun, lettuce, tomato, onion, mayonnaise, and ketchup."
  },
  {
    id: 15,
    name: 'Cheese Burger',
    ingredients: 'Beef, Cheese, Lettuce, Vegetables',
    price: '6.90',
    person: 1,
    duration: 0.25,
    categoryid: 2,
    image: require('../../assets/food/cheese-burger.jpg'),
    details: "A classic cheeseburger with a juicy beef patty topped with cheddar cheese, fresh lettuce, and a savory sauce. Served with a soft, toasted bun.",
  },
  {
    id: 16,
    name: 'Margarita Pizza',
    ingredients: 'Tomato, Mozzarella, Basil,  Oil',
    price: '6.50',
    person: 3,
    duration: 0.55,
    categoryid: 3,
    image: require('../../assets/food/margherita-pizza.jpg'),
    details: "The classic Margherita pizza topped with fresh tomatoes, mozzarella cheese, and basil. A timeless favorite for pizza lovers.",
  },
  {
    id: 17,
    name: 'Caesar Salad',
    ingredients: ' Lettuce,  Crouton, Lemon, Oil',
    price: '5.60',
    person: 1,
    duration: 0.17,
    categoryid: 4,
    image: require('../../assets/food/Caesar-Salad.jpg'),
    details: "A fresh Caesar salad with crisp romaine lettuce, golden croutons, and creamy Caesar dressing. Topped with parmesan shavings.",
  },

  {
    id: 18,
    name: 'Veggie Pizza',
    ingredients: 'Bell Pepper, Olives, Onion',
    price: '6.80',
    person: 3,
    duration: 0.20,
    categoryid: 3,
    image: require('../../assets/food/vegetarian-pizza.jpg'),
    details: "A delightful vegetarian pizza topped with a mix of colorful bell peppers, sliced black olives, and red onions.",
  },
  {
    id: 19,
    name: 'Greek Salad',
    ingredients: 'Olives, Feta Cheese, Tomatoes',
    price: '5.75',
    person: 1,
    duration: 0.17,
    categoryid: 4,
    image: require('../../assets/food/Greek-Salad.jpg'),
    details: "A refreshing salad made with ripe tomatoes, cucumbers, red onions, black olives, and feta cheese. Dressed with olive oil and oregano.",
  },

  {
    id: 20,
    name: 'Bhindi Dopiaza',
    ingredients: 'Okra, Spices, Salt',
    price: '8.30',
    person: 4,
    duration: 0.35,
    categories: 'Indian',
    image: require('../../assets/food/bhindi.jpg'),
    details: "Bhindi Dopiaza is a flavorful Indian dish that features okra (bhindi) cooked with a generous amount of onions, spices, and a rich tomato-based gravy.",
  },

  {
    id: 21,
    name: 'Egg Curry',
    ingredients: 'Egg, Onions, Tomato, Spices, Garlic',
    price: '10.55',
    person: 4,
    duration: 0.30,
    categories: 'Indian',
    image: require('../../assets/food/EggCurry.jpg'),
    details: "Egg curry is a popular and flavorful Indian dish made with boiled eggs in a spiced tomato-based gravy.",
  },


];






export { foods, categories, icons };